[package]
name = "bytewax"
version = "0.11.1"
edition = "2021"

[lib]
name = "bytewax"
crate-type = ["cdylib", "rlib"]

[package.metadata.maturin]
python-source = "pysrc"

[dependencies]
bincode = { version = "1.3.3" }
chrono = { version = "0.4", features = [ "serde" ] }
futures = { version = "0.3.21" }
log = { version = "0.4" }
pyo3 = { version = "0.17.1" }
pyo3-chrono = { version = "0.5.0" }
pyo3-log = { version = "0.7.0" }
scopeguard = { version = "1.1.0" }
send_wrapper = { version = "0.6.0" }
serde = { version = "1.0.134" }
serde_test = { version = "1.0.134" }
sqlx = { version = "0.6.1", features = [ "runtime-tokio-rustls", "postgres", "sqlite" ] }
timely = { version = "0.12.0", features = [ "bincode" ] }
tokio = { version = "1.20.1", features = [ "full" ] }

# For macos, use vendored gssapi
[target.'cfg(target_os = "macos")'.dependencies]
rdkafka = { version = "0.28.0", features = [ "cmake-build", "gssapi-vendored", "ssl-vendored" ] }

# For everything else, use system sasl-lib
[target.'cfg(not(target_os = "macos"))'.dependencies]
rdkafka = { version = "0.28.0", features = [ "cmake-build", "gssapi", "ssl" ] }

[dev-dependencies]
pyo3 = { version = "0.17.1", default-features = false }

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
