name: CI

on:
  push:
    branches:
    - main
  pull_request: {}

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install libssl-dev libsasl2-dev pkg-config openssl
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.61
    - name: Install dill
      shell: bash
      run: |
        pip install dill
    - name: Rust tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-default-features
    - uses: messense/maturin-action@v1
      with:
        rust-toolchain: 1.61
        manylinux: auto
        container: off
        command: build
        args: --release -o dist --interpreter python${{ matrix.python-version }}
    - name: Run tests
      shell: bash
      run: |
        WHEEL_FILE=$(ls ./dist/*.whl)
        pip install $WHEEL_FILE -v
        pip install -r build.requirements.txt
        pytest
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install system dependencies
      run: |
        brew update
        HOMEBREW_NO_INSTALL_CLEANUP=1 brew install cyrus-sasl
        HOMEBREW_NO_INSTALL_CLEANUP=1 brew reinstall openssl@1.1
        echo "OPENSSL_ROOT_DIR"=/usr/local/opt/openssl@1.1 >> $GITHUB_ENV
        echo "SASL2_DIR"=/usr/local/opt/cyrus_sasl >> $GITHUB_ENV
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.61
    - name: Install system dependency
      shell: bash
      run: |
        pip install dill
    - name: Rust tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-default-features
    - uses: messense/maturin-action@v1
      with:
        rust-toolchain: 1.61
        command: build
        args: --release --no-sdist -o dist --universal2 --interpreter python${{ matrix.python-version }}
    - name: Run tests
      shell: bash
      run: |
        WHEEL_FILE=$(ls ./dist/*.whl)
        pip install $WHEEL_FILE -v
        pip install -r build.requirements.txt
        pytest
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist

  upload:
    name: Store wheels in S3
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/main'"
    needs: [ linux, macos ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
          path: wheels
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_KEY }}
          aws-region: us-west-2
      - name: Upload files to S3 with AWS CLI
        run: |
          aws s3 sync ./wheels s3://${{ secrets.WHEELS_S3_BUCKET }}/${{ github.sha }} --delete
          aws s3 ls s3://${{ secrets.WHEELS_S3_BUCKET }}/${{ github.sha }}
