name: issue-automation

on:
  issues:
    types: [opened]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "needs-triage"
          ignore-if-assigned: true
